### ISSUE TITLE
Extreme input lag reduce issue

### ISSUE THREAD

**Issue by nomaxfun** [forkymcforkface/RGBPi-Extra#25]
When replacing the fceumm emulator with mesen extreme latency reduction works fine, but if mesen is updated via core updater, the games don't launch. 
Also the updated genesis_plus_gx doesn't work well with the same feature (I have a noticeable problem on Earthworm Jim)

**Comment by riggles1** [comment]
Run-ahead is too heavy for mesen (much better gfx+audio accuracy than fceumm but at the cost of processing), that said you're getting between 1 to 2 frames of input lag anyway and no frame drops without any reduction on.

genesis_plus_gx also is too much for runahead to work without performance issues like crackling audio and skipped frames, same there, run it without runahead on. The latency reduction is very processing expensive and too much for the pi.

The updated cores are newer and more accurate so I suggest using them over the default older cores. But the cost of lost accuracy isn't worth it to run old or less accurate cores.

In OS4 there's a input lag reduction option somewhere which is what you're talking about, all it does is globally enable runahead within retroarch, turn it off, it's awful. "extreme" sets runahead to something like 3 frames, which is beyond what the actual input lag is in the first place. (you end up skipping to a point in time when you're character is already a frame in the air after pressing jump, giving you a jitter)

In any case, runahead doesn't work with all games due to not all games having built in frames of latency within their gameplay that you can cut back on (runahead "fast forwards" the game at the moment you press a button to cut latency)

This feature is too expensive and unreliable to have enabled for all games, the 1-2 frames of input latency that you have without it turned on is nothing really.

**Comment by nomaxfun** [comment]
The updated mesen doesn't run games anyway, no matter what latency reduction is enabled

**Comment by riggles1** [comment]
That's a different issue then, maybe something went wrong with the core updater copying the files. In "RGBPi-Extra\application\data\update_cores" there's a mesen_libretro.7z, extract this, and place the mesen_libretro.so core file inside of "opt\retroarch\cores" replace it there, accessible through WinSCP. 
either:
user:rguipi password:rgbpi
or
user:root password:rgbpi

Test if that works, the core is functional.
